export const SWActionTypes = {
  FETCH_PLANETS_START: 'FETCH_PLANETS_START',
  FETCH_PEOPLE_START: 'FETCH_PEOPLE_START',
  FETCH_PEOPLE_SUCCESS: 'FETCH_PEOPLE_SUCCESS',
  FETCH_PLANETS_SUCCESS: 'FETCH_PLANETS_SUCCESS',
  FETCH_PEOPLE_FAILURE: 'FETCH_PLANETS_FAILURE',
  FETCH_PLANETS_FAILURE: 'FETCH_PLANETS_FAILURE',
  START_LOADING: 'START_LOADING',
  STOP_LOADING: 'STOP_LOADING',
  CLEAR_DATA: 'CLEAR_DATA',
}
